FROM node:7.1.0

WORKDIR /home/app/src

RUN groupadd -r nroot -g 433 && \
useradd -u 431 -r -g nroot -d /home/app/src -c "Docker image user" nroot && \
chown -R nroot:nroot /home/app/src && \

VOLUME /home/app/src
